### ISSUE TITLE
Potential Filtering Issue with AJAXSelect2Field

### ISSUE THREAD

**Issue by carlaiau** [sheadawson/silverstripe-select2#10]
I have an ExactMatch Filter which was not been applied through the config system. I don't think ExactMatch Filtering after FilterAny works I changed line 48 of AJAXSelect2Field.php from this:

      $list = $list->filterAny($params)->exclude($this->getConfig('excludes'));
        $filter = $this->getConfig('filter');
        if (count($filter) > 0) {
            $list->filter($filter);
        }

to:

       $filter = $this->getConfig('filter');
        if (count($filter) > 0) {
	        $list = $list->filter($filter)->filterAny($params)->exclude($this->getConfig('excludes'));
        }
        else{
	       	$list = $list->filterAny($params)->exclude($this->getConfig('excludes'));
        }

**Comment by sheadawson** [comment]
Hmm... I think just changing 

```$list->filter($filter);```

to

```$list  = $list->filter($filter);```

Should fix this bug. Can you confirm that for me?

Cheers :)

**Comment by Jntz** [comment]
@sheadawson, I add pull request about this filter issue
https://github.com/sheadawson/silverstripe-select2/pull/11

**Comment by sheadawson** [comment]
Fixed in #11
